name: test
on: [push]
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - run: go version
      - run: go mod download
      - run: go build ./
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - run: go version
      - run: go mod download
      - run: go vet ./
